-- MySQL Script generated by MySQL Workbench
-- lun. 01 juin 2020 15:16:42 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portfolio_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfolio_db` ;

-- -----------------------------------------------------
-- Schema portfolio_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio_db` DEFAULT CHARACTER SET utf8 ;
USE `portfolio_db` ;

-- -----------------------------------------------------
-- Table `portfolio_db`.`bio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_db`.`bio` ;

CREATE TABLE IF NOT EXISTS `portfolio_db`.`bio` (
  `image_link` TINYTEXT NULL,
  `cv_link` TINYTEXT NULL,
  `intro` VARCHAR(45) NULL,
  `toolbox` VARCHAR(45) NULL,
  `experience` VARCHAR(45) NULL,
  `education` VARCHAR(45) NULL);


-- -----------------------------------------------------
-- Table `portfolio_db`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_db`.`projects` ;

CREATE TABLE IF NOT EXISTS `portfolio_db`.`projects` (
  `id` INT(150) NOT NULL,
  `name` VARCHAR(255) NULL,
  `technologies` VARCHAR(45) NULL,
  `description` TEXT(800) NULL,
  `youtube_link` VARCHAR(255) NULL,
  `github_link` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `portfolio_db`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_db`.`table1` ;

CREATE TABLE IF NOT EXISTS `portfolio_db`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_db`.`user` ;

CREATE TABLE IF NOT EXISTS `portfolio_db`.`user` (
  `username` VARCHAR(45) NULL,
  `intro` TEXT(500) NULL,
  `email` VARCHAR(50) NULL,
  `email2` VARCHAR(45) NULL,
  `password` VARCHAR(10) NULL,
  `phone` VARCHAR(45) NULL);


-- -----------------------------------------------------
-- Table `portfolio_db`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_db`.`projects` ;

CREATE TABLE IF NOT EXISTS `portfolio_db`.`projects` (
  `id` INT(150) NOT NULL,
  `name` VARCHAR(255) NULL,
  `technologies` VARCHAR(45) NULL,
  `description` TEXT(800) NULL,
  `youtube_link` VARCHAR(255) NULL,
  `github_link` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `portfolio_db`.`bio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_db`.`bio` ;

CREATE TABLE IF NOT EXISTS `portfolio_db`.`bio` (
  `image_link` TINYTEXT NULL,
  `cv_link` TINYTEXT NULL,
  `intro` VARCHAR(45) NULL,
  `toolbox` VARCHAR(45) NULL,
  `experience` VARCHAR(45) NULL,
  `education` VARCHAR(45) NULL);


-- -----------------------------------------------------
-- Table `portfolio_db`.`toolbox_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_db`.`toolbox_item` ;

CREATE TABLE IF NOT EXISTS `portfolio_db`.`toolbox_item` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `sortcut` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
